# Question 01:
###### Create a one-dimensional NumPy array containing integers from 1 to 10. Compute the sum, mean, and product of the array.

In [7]:
import numpy as np
array = np.arange(1, 11)
print("The array is: ", array)
mean = np.mean(array)
product = np.prod(array)
sum = np.sum(array)

print(f"Sum: {sum}\nMean: {mean}\nMultiplication: {product}")


The array is:  [ 1  2  3  4  5  6  7  8  9 10]
Sum: 55
Mean: 5.5
Multiplication: 3628800


# Quetion 02:
###### Generate a 3x3 matrix with random integers. Calculate the transpose of the matrix.

In [12]:
matrix = np.random.randint(1, 10, size=(3,3))
print("The matrix is:\n", matrix)

transpose = np.transpose(matrix)
print("The transpose of matrix is:\n", transpose)

The matrix is:
 [[5 1 1]
 [9 7 5]
 [7 3 4]]
The transpose of matrix is:
 [[5 9 7]
 [1 7 3]
 [1 5 4]]


# Question 03:
###### Create a NumPy array with 20 values and reshape it into a 4x5 matrix.

In [14]:
array = np.arange(1, 21)
print("The array before reshaping: ", array)

array = array.reshape(4, 5)
print("The reshaped array into (4x5) is:\n", array)

The array before reshaping:  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
The reshaped array into (4x5) is:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


# Question 04:
###### Perform element-wise addition, subtraction, multiplication, and division on two NumPy arrays of your choice.

In [27]:
A = np.random.randint(1, 20, 8)
B = np.random.randint(1, 20, 8)

print("The first Array is: ", A)
print("The second Array is: ", B)

sum = np.add(A, B)
product = np.multiply(A, B)
subtraction = np.subtract(A, B)
division = np.divide(A, B)

print(f"The sum is: {sum}\nMultiplied elements array: {product}\nSubtracted elements array: {subtraction}\nDivided elements array: {division}\n")



The first Array is:  [ 7 19 11 13  2  8  3 16]
The second Array is:  [ 8  7  3 16 17  2  7 13]
The sum is: [15 26 14 29 19 10 10 29]
Multiplied elements array: [ 56 133  33 208  34  16  21 208]
Subtracted elements array: [ -1  12   8  -3 -15   6  -4   3]
Divided elements array: [0.875      2.71428571 3.66666667 0.8125     0.11764706 4.
 0.42857143 1.23076923]



# Question 05:
###### Create a NumPy array of 10 values and apply the square root function to each element.

In [32]:
array = np.array([1, 4, 9, 16, 49, 81, 121, 25, 36, 64])
sq_root_array = np.sqrt(array)
print(f"Original array: {array}\nSquare rooted array: {sq_root_array}")


Original array: [  1   4   9  16  49  81 121  25  36  64]
Square rooted array: [ 1.  2.  3.  4.  7.  9. 11.  5.  6.  8.]


# Question 06:
###### Generate a 2x2 matrix and calculate its determinant and inverse.

In [52]:
matrix = np.random.randint(1, 10, 4).reshape(2, 2)
determinant = int(np.linalg.det(matrix))

if determinant != 0:
    inverse = np.linalg.inv(matrix)
else:
    print("Inverse is not possible\n")
    inverse = None

print(f"The matrix is:\n{matrix}\nInverse:\n{inverse}\nDeterminant Of Matrix is: {determinant}")

The matrix is:
[[1 9]
 [3 6]]
Inverse:
[[-0.28571429  0.42857143]
 [ 0.14285714 -0.04761905]]
Determinant Of Matrix is: -21


# Question 07:
###### Create a NumPy array with 50 random values. Find the indices of the maximum and minimum values in the array.

In [80]:
arr = np.random.randint(1, 500, 50)
max_index = np.argmax(arr)
min_index = np.argmin(arr)

print("The array is: ", arr)
print(f"The maximum value index is : {max_index}\nThe minimum value index is: {min_index}")

The array is:  [340 489 498 305 317 176  14 485 472   5 119 127 397 278 241  62 212 234
 419  62 113 359 194 372  86 216  49  95  74 213 456 484 316 327 452 222
 480 273 368 425  91 487 276 147 463 269  95 425  95 472]
The maximum value index is : 2
The minimum value index is: 9


# Question 08:
###### Create a 3x3 matrix representing a system of linear equations. Use NumPy to solve the system and print the solution.

In [83]:
#Ax=b
A = np.array([[2, 3, 1],
              [4, 1, 6],
              [1, 5, 2]])

b = np.array([1, 2, 3])

solution = np.linalg.solve(A, b)

print("The solution for the system of equations is:")
print(f"x = {solution[0]}, y = {solution[1]}, z = {solution[2]}")


The solution for the system of equations is:
x = -0.4883720930232557, y = 0.46511627906976744, z = 0.5813953488372092


# Question 09:
###### Create a NumPy array with 25 values and calculate the 75th percentile.

In [87]:
arr = np.random.randint(1, 100, 25)

percentile_75th = np.percentile(arr, 75)
print(f"The array is: {arr}\n75th percentile of array is: {percentile_75th}")

The array is: [40 27 11 96 48 79 17 30 91 59 97 77 99 12 19 75 51 47 77 17 72 87 52 72
  2]
75th percentile of array is: 77.0


# Question 10:
###### Implement a function that accepts a NumPy array and normalizes it (subtracts the mean and divides by the standard deviation). Apply this function to a sample array.

In [91]:
def normalize_array(arr):
    mean = np.mean(arr)
    std_deviation = np.std(arr)
    normalized = np.divide((np.subtract(arr, mean)), std_deviation)
    
    return normalized

array = np.random.randint(1, 10, 8)
normalized_array_result = normalize_array(array)

print(f"Original array is: {array}\nThe Normalized array is: {normalized_array_result}")


Original array is: [7 9 3 9 9 5 7 6]
The Normalized array is: [ 0.06166264  1.04826491 -1.91154189  1.04826491  1.04826491 -0.92493962
  0.06166264 -0.43163849]
